### ISSUE TITLE
New internet explorer issues..

### ISSUE THREAD

**Issue by ShiroGaijin** [goFrendiAsgard/No-CMS#141] opened 2015-10-16 11:00 UTC
since updating no-cms, internet explorer crashes because of javascript on main index page, and there is no static contet box when editing a page :(

**Comment by goFrendiAsgard** [comment] 2015-10-16 11:12
try to press ctrl + F5

**Comment by goFrendiAsgard** [comment] 2015-10-16 14:19
Try with this one: https://github.com/goFrendiAsgard/No-CMS/tree/a874ffefc58ba538a2daf05129e07db5d5bde8ad

**Comment by ShiroGaijin** [comment] 2015-10-19 16:19
after a clean install, in internet explorer the site is displaying the mobile dropdown button and the images are huge in the index page, script on dropdown causes an error,which says the useragent is mozilla which it isnt. :(

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; BTRS102284; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET CLR 1.1.4322)
Timestamp: Mon, 19 Oct 2015 16:17:05 UTC


Message: Object doesn't support this property or method
Line: 198
Char: 33
Code: 0
URI: http://welshwebwizardry.co.uk/

**Comment by goFrendiAsgard** [comment] 2015-10-22 00:36
Need some more inspection on this

**Comment by ShiroGaijin** [comment] 2015-10-22 17:04
simply use internet explorer and install a new build, it's a big problem.

**Comment by goFrendiAsgard** [comment] 2015-10-23 02:23
We use use ubuntu for our daily basis. Still need a way to install IE in ubuntu.
BTW, do you use IE 11?

**Comment by ShiroGaijin** [comment] 2015-10-28 13:31
i use IE 9, mostly use firefox.

**Comment by goFrendiAsgard** [comment] 2015-10-29 11:10
![screenshot from 2015-10-29 18 06 02](https://cloud.githubusercontent.com/assets/883662/10816745/d77b4914-7e67-11e5-984f-b992213e2972.png)

I'm using browserstack to emulate IE. However The problem seems only appeared at IE8 on windows 7. I'm so sorry I'm unable to find any computer using windows in my office :(

Please try to open http://getnocms.com with IE9. Is the problem still persists?
If it is not, then I'm afraid the problem is caused by some javascript or css in your custom theme.

**Comment by goFrendiAsgard** [comment] 2015-11-05 12:23
Got some insight:
http://stackoverflow.com/questions/17947182/ie8-issue-with-twitter-bootstrap-3
and
https://github.com/scottjehl/Respond
Gotta work with this later

**Comment by goFrendiAsgard** [comment] 2015-11-05 16:29
Should be fixed by now: https://github.com/goFrendiAsgard/No-CMS/tree/9ba8cac9a25fd4805a66252bcc7dd4e0473cafb2

**Closed by goFrendiAsgard** 2015-11-05 16:29 UTC
